#!/usr/bin/env node
// Merge the scraped source fragments in tools/data/ into the site's feed.
//
//   node build-matches.mjs [--out ../vercel-deploy/data/matches.json]
//                          [--all] [--since YYYY-MM-DD] [--quiet]
//
// Reads every `data/*.json` fragment written by a scraper and produces
// `{ generatedAt, sources, matches }` — the contract the page reads.
//
// STA is deliberately absent: api.singtennis.org.sg is public and CORS-open,
// so the browser imports it directly and there is nothing to scrape. This
// merger exists for sources the browser cannot reach, which today means JTTL.
//
// By default finished fixtures are dropped. JTTL publishes every team fixture
// in every division — 222 of them for one past season — and shipping that as
// the site's feed buries the handful of dates you can still plan around. Use
// --all to keep the history.

import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { dirname, resolve, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = resolve(here, 'data');

function parseArgs(argv) {
  const args = {
    out: resolve(here, '../vercel-deploy/data/matches.json'),
    all: false,
    since: null,
    quiet: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') args.out = resolve(argv[++i]);
    else if (a === '--all') args.all = true;
    else if (a === '--since') args.since = argv[++i];
    else if (a === '--quiet') args.quiet = true;
    else if (a === '--help' || a === '-h') args.help = true;
    else throw new Error(`unknown flag: ${a}`);
  }
  return args;
}

const ISO = /^\d{4}-\d{2}-\d{2}$/;

// Mirrors the validation the page applies, so nothing reaches the site that it
// would silently drop anyway.
function validMatch(m) {
  return m && typeof m === 'object' &&
    typeof m.id === 'string' && m.id &&
    typeof m.name === 'string' && m.name &&
    ISO.test(m.start);
}

function normalise(m) {
  return {
    id: m.id,
    source: typeof m.source === 'string' ? m.source : 'unknown',
    name: m.name,
    start: m.start,
    end: ISO.test(m.end) ? m.end : m.start,
    venue: typeof m.venue === 'string' ? m.venue : '',
    categories: Array.isArray(m.categories) ? m.categories.filter(c => typeof c === 'string') : [],
    entryDeadline: ISO.test(m.entryDeadline) ? m.entryDeadline : null,
    url: typeof m.url === 'string' ? m.url : '',
    provisional: m.provisional === true,
    ...(typeof m.note === 'string' && m.note ? { note: m.note } : {}),
  };
}

function today() {
  const d = new Date();
  const p = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log('usage: node build-matches.mjs [--out PATH] [--all] [--since YYYY-MM-DD] [--quiet]');
    return;
  }
  const log = (...a) => { if (!args.quiet) console.log(...a); };
  const cutoff = args.all ? null : (args.since && ISO.test(args.since) ? args.since : today());

  let files;
  try {
    files = (await readdir(DATA_DIR)).filter(f => f.endsWith('.json')).sort();
  } catch {
    files = [];
  }
  if (!files.length) throw new Error(`no source fragments in ${DATA_DIR} — run a scraper first`);

  const sources = [];
  const seen = new Map();
  let dropped = 0, invalid = 0;

  for (const file of files) {
    const raw = JSON.parse(await readFile(join(DATA_DIR, file), 'utf8'));
    const list = Array.isArray(raw.matches) ? raw.matches : [];
    let kept = 0;
    for (const m of list) {
      if (!validMatch(m)) { invalid++; continue; }
      const rec = normalise(m);
      // Keep anything still ahead of the cutoff, and always keep provisional
      // records: they exist precisely because the real dates are not out yet.
      if (cutoff && rec.end < cutoff && !rec.provisional) { dropped++; continue; }
      if (seen.has(rec.id)) continue;
      seen.set(rec.id, rec);
      kept++;
    }
    sources.push({
      id: raw.source || basename(file, '.json'),
      fetchedAt: raw.fetchedAt || null,
      ok: raw.ok !== false,
      count: kept,
    });
    log(`  ${file}: ${kept} kept of ${list.length}`);
  }

  const matches = [...seen.values()].sort((a, b) =>
    a.start < b.start ? -1 : a.start > b.start ? 1 : a.name.localeCompare(b.name));

  // A feed that silently went empty looks exactly like a free year.
  if (!matches.length) {
    throw new Error('every source produced zero matches — refusing to write an empty feed');
  }

  const payload = {
    _comment: 'GENERATED by tools/build-matches.mjs. Do not edit by hand.',
    generatedAt: new Date().toISOString(),
    sources,
    matches,
  };
  await mkdir(dirname(args.out), { recursive: true });
  await writeFile(args.out, `${JSON.stringify(payload, null, 2)}\n`);

  const prov = matches.filter(m => m.provisional).length;
  log(`\nwrote ${args.out}`);
  log(`  ${matches.length} matches (${prov} provisional)` +
      (cutoff ? `, ${dropped} finished before ${cutoff} dropped — use --all to keep them` : ''));
  if (invalid) log(`  ${invalid} malformed records skipped`);
}

main().catch(err => {
  console.error(`build-matches: ${err.message}`);
  process.exit(1);
});
